name: Build and Push Docker Image

on:
  schedule:
    # 每天的 UTC 时间 0 点构建
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: 'Lhcfl/sharkey-stelpolva' # 替换为目标公开项目的 GitHub 仓库
          ref: stelpolva # 确保检查出特定的分支

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # 在 GitHub Secrets 中配置
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # 在 GitHub Secrets 中配置

      - name: Build Docker Image
        run: |
          docker build -t wuhang2003/sharkey-stelpolva-docker:latest . # 替换为你的 DockerHub 用户名和镜像名称

      - name: Push Docker Image to Docker Hub
        run: |
          docker push wuhang2003/sharkey-stelpolva-docker:latest # 替换为你的 DockerHub 用户名和镜像名称

