name: Build and Push Docker Image

on:
  schedule:
    # 每天的 UTC 时间 0 点构建
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME: wuhang2003/sharkey-stelpolva-docker

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: 'Lhcfl/sharkey-stelpolva' # 替换为目标公开项目的 GitHub 仓库
          ref: stelpolva # 确保检查出特定的分支
          submodules: true
          lfs: true
 
      - name: Fetch package version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV         

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: files
          
      - name: Check if commit SHA has changed
        id: check_hash
        working-directory: files
        run: |
          if [ -f hash ] && [ "$(cat hash)" = "${{ env.COMMIT_SHA }}" ]; then
            echo "Commit SHA has not changed. Skipping build."
            echo "continue=false" >> $GITHUB_OUTPUT
          else
            echo "Commit SHA has changed. Proceeding with build."
            echo "continue=true" >> $GITHUB_OUTPUT
          fi

      - name: Update hash file
        if: steps.check_hash.outputs.continue == 'true'
        run: |
          echo "${{ env.COMMIT_SHA }}" > files/hash
      
      - name: Commit and push hash file
        if: steps.check_hash.outputs.continue == 'true'
        working-directory: files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hash
          git commit -m "Update commit SHA to ${{ env.COMMIT_SHA }}"
          
      - name: Push changes
        if: steps.check_hash.outputs.continue == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: miaoa-dev/sharkey-stelpolva-docker
          directory: files
    
      - name: Log in to Docker Hub
        if: steps.check_hash.outputs.continue == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # 在 GitHub Secrets 中配置
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # 在 GitHub Secrets 中配置
          
      - name: Docker meta
        if: steps.check_hash.outputs.continue == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME}}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,format=long
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: Build and push
        if: steps.check_hash.outputs.continue == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        if: steps.check_hash.outputs.continue == 'true'
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
